name: CI - Backend & Frontend (Build + Test + Push)

on:
  pull_request:
    branches: [main, dev]
  push:
    branches:
      - dev
      - main

env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  ACR_NAME: ${{ secrets.ACR_NAME }}
  IMAGE_TAG: ${{ github.sha }}

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    name: Backend CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install -r backend/product_service/requirements.txt
          pip install -r backend/order_service/requirements.txt
          pip install pytest httpx

      - name: Run product tests
        working-directory: backend/product_service
        run: pytest -q

      - name: Run order tests
        working-directory: backend/order_service
        run: pytest -q

      - name: Azure Login (main only)
        if: github.ref == 'refs/heads/main'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR (main only)
        if: github.ref == 'refs/heads/main'
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Build & Push backend images (main only)
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/product_service:latest ./backend/product_service
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/order_service:latest   ./backend/order_service
          docker push ${{ env.ACR_LOGIN_SERVER }}/product_service:latest
          docker push ${{ env.ACR_LOGIN_SERVER }}/order_service:latest

  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login (main only)
        if: github.ref == 'refs/heads/main'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR (main only)
        if: github.ref == 'refs/heads/main'
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Build & Push frontend image (main only)
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/frontend:latest ./frontend
          docker push ${{ env.ACR_LOGIN_SERVER }}/frontend:latest

